package vn.com.vti.springexam.entity;

import java.util.Date;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_id
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    private String bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_name
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.price
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.discount
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    private Integer discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.category_id
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    private String categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publisher_id
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    private String publisherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.page_count
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    private Integer pageCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.isbn13
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    private String isbn13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.on_sale_date
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    private Date onSaleDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_id
     *
     * @return the value of book.book_id
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    public String getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_id
     *
     * @param bookId the value for book.book_id
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    public void setBookId(String bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_name
     *
     * @return the value of book.book_name
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_name
     *
     * @param bookName the value for book.book_name
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.price
     *
     * @return the value of book.price
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.price
     *
     * @param price the value for book.price
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.discount
     *
     * @return the value of book.discount
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.discount
     *
     * @param discount the value for book.discount
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.category_id
     *
     * @return the value of book.category_id
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.category_id
     *
     * @param categoryId the value for book.category_id
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.publisher_id
     *
     * @return the value of book.publisher_id
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    public String getPublisherId() {
        return publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.publisher_id
     *
     * @param publisherId the value for book.publisher_id
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    public void setPublisherId(String publisherId) {
        this.publisherId = publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.page_count
     *
     * @return the value of book.page_count
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    public Integer getPageCount() {
        return pageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.page_count
     *
     * @param pageCount the value for book.page_count
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    public void setPageCount(Integer pageCount) {
        this.pageCount = pageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.isbn13
     *
     * @return the value of book.isbn13
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    public String getIsbn13() {
        return isbn13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.isbn13
     *
     * @param isbn13 the value for book.isbn13
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    public void setIsbn13(String isbn13) {
        this.isbn13 = isbn13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.on_sale_date
     *
     * @return the value of book.on_sale_date
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    public Date getOnSaleDate() {
        return onSaleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.on_sale_date
     *
     * @param onSaleDate the value for book.on_sale_date
     *
     * @mbg.generated Sat Sep 10 22:36:50 JST 2022
     */
    public void setOnSaleDate(Date onSaleDate) {
        this.onSaleDate = onSaleDate;
    }
}