package vn.com.vti.springexam.entity;

public class Section3 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section3.id
     *
     * @mbg.generated Mon Sep 19 23:32:41 JST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section3.name
     *
     * @mbg.generated Mon Sep 19 23:32:41 JST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section3.id
     *
     * @return the value of section3.id
     *
     * @mbg.generated Mon Sep 19 23:32:41 JST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section3.id
     *
     * @param id the value for section3.id
     *
     * @mbg.generated Mon Sep 19 23:32:41 JST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section3.name
     *
     * @return the value of section3.name
     *
     * @mbg.generated Mon Sep 19 23:32:41 JST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section3.name
     *
     * @param name the value for section3.name
     *
     * @mbg.generated Mon Sep 19 23:32:41 JST 2022
     */
    public void setName(String name) {
        this.name = name;
    }
}