package vn.com.vti.springexam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.springexam.entity.Infrastructure;
import vn.com.vti.springexam.entity.InfrastructureExample;

public interface InfrastructureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infrastructure
     *
     * @mbg.generated Mon Sep 12 06:06:58 JST 2022
     */
    long countByExample(InfrastructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infrastructure
     *
     * @mbg.generated Mon Sep 12 06:06:58 JST 2022
     */
    int deleteByExample(InfrastructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infrastructure
     *
     * @mbg.generated Mon Sep 12 06:06:58 JST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infrastructure
     *
     * @mbg.generated Mon Sep 12 06:06:58 JST 2022
     */
    int insert(Infrastructure row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infrastructure
     *
     * @mbg.generated Mon Sep 12 06:06:58 JST 2022
     */
    int insertSelective(Infrastructure row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infrastructure
     *
     * @mbg.generated Mon Sep 12 06:06:58 JST 2022
     */
    List<Infrastructure> selectByExample(InfrastructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infrastructure
     *
     * @mbg.generated Mon Sep 12 06:06:58 JST 2022
     */
    Infrastructure selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infrastructure
     *
     * @mbg.generated Mon Sep 12 06:06:58 JST 2022
     */
    int updateByExampleSelective(@Param("row") Infrastructure row, @Param("example") InfrastructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infrastructure
     *
     * @mbg.generated Mon Sep 12 06:06:58 JST 2022
     */
    int updateByExample(@Param("row") Infrastructure row, @Param("example") InfrastructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infrastructure
     *
     * @mbg.generated Mon Sep 12 06:06:58 JST 2022
     */
    int updateByPrimaryKeySelective(Infrastructure row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infrastructure
     *
     * @mbg.generated Mon Sep 12 06:06:58 JST 2022
     */
    int updateByPrimaryKey(Infrastructure row);
}